### ISSUE TITLE
Look for Grants/Funding sources 

### ISSUE THREAD

**Issue by lmberkhout** [astrochart/CHART#134]
Look through the NSF, ASU individual scholarships, etc.

**Comment by lmberkhout** [comment]
https://www.grants.gov/web/grants/view-opportunity.html?oppId=320374

**Comment by lmberkhout** [comment]
https://www.grants.gov/web/grants/view-opportunity.html?oppId=319933

**Comment by adampbeardsley** [comment]
This would require a lot more work into recruitment/retention research, but worth looking at:
https://www.nsf.gov/funding/pgm_summ.jsp?pims_id=505632&org=NSF&sel_org=NSF&from=fund

**Comment by adampbeardsley** [comment]
PFE: Research Initiation in Engineering Formation (PFE: RIEF)
https://www.nsf.gov/pubs/2020/nsf20558/nsf20558.htm?WT.mc_id=USNSF_25&WT.mc_ev=click

**Comment by adampbeardsley** [comment]
I think ASU and WSU have money for now. Closing
