### ISSUE TITLE
RTL-SDR Blog v4 dongle support

### ISSUE THREAD

**Issue by adampbeardsley** [astrochart/CHART#203]
The new RTL-SDR.com blog dongle is out, but they have not pushed the drivers to osmosdr yet. I'm going to try and get it working, and document my progress here.

**Comment by EphemeralDisco** [comment]
Instructions for v4 driver installation are here: https://www.rtl-sdr.com/v4/

For *nix:
The first set of instructions for Linux (Debian) did not work for me. The second set of instructions using packages did work. Copied below:
Update RTL-SDR driver to v4:
sudo apt update
sudo apt install libusb-1.0-0-dev git cmake
sudo apt install debhelper

git clone https://github.com/rtlsdrblog/rtl-sdr-blog
cd rtl-sdr-blog
sudo dpkg-buildpackage -b --no-sign
cd ..

sudo dpkg -i librtlsdr0_*.deb
sudo dpkg -i librtlsdr-dev_*.deb
sudo dpkg -i rtl-sdr_*.deb

**Comment by adampbeardsley** [comment]
I was able to get it to work using the first set of instructions on https://www.rtl-sdr.com/v4/

I tested things using a simple gnu radio companion flowgraph:
![image](https://github.com/astrochart/CHART/assets/4752917/58aeba8a-d9ca-4675-945a-5f404e1e4161)

Here was my test data using v3 dongle, tuned to a local radio station (seen very weakly at 89.5 MHz), plus the RF explorer transmitting at 89.7 MHz (unsure why it's showing up at 89.6 MHz).
![image](https://github.com/astrochart/CHART/assets/4752917/131cfef4-5e9d-423d-b91f-345fad99a32c)

Before installing the new driver, the flowgraph happily ran using the v4 dongle, but produced no signal:
![image](https://github.com/astrochart/CHART/assets/4752917/f6fc8bfc-bb74-445d-8283-dc47dd06902c)
(note I forgot to set the "Display RF Frequencies" button, but it's tuned the same as the first dataset.)

After going through the instructions on rtl-sdr.com/v4, and relaunching GRC, I got a missing block error. 
I reran this line:
`sudo apt install gnuradio-dev gr-osmosdr librtlsdr-dev`

And now everything seems to work. New data test:
![image](https://github.com/astrochart/CHART/assets/4752917/7ec555fa-3b6f-41e5-9f02-2d6844c9e7cc)

And to be sure, I ran the chart data collection with the RF explorer transmitting at 1419.7 MHz:
![image](https://github.com/astrochart/CHART/assets/4752917/e3213383-a6bf-4f6b-8a9b-6c5c10781930)
The bias-T was successfully enabled, and we get a nice bright line at the correct frequency. This was done in the lab, so there's a ton of other cruff, unsurprisingly.
