### ISSUE TITLE
Bias-T Instructions

### ISSUE THREAD

**Issue by lmberkhout** [astrochart/CHART#209]
Be more clear about what the Bias-T is and when it is used, so your students don't forget to turn the amplifiers on!

**Comment by adampbeardsley** [comment]
Is this meant to go on the website? Or are you asking for clarification in the GUI?

**Comment by lmberkhout** [comment]
Both would be good

**Comment by lmberkhout** [comment]
redundancy is always nice

**Comment by Alexandra202421** [comment]
I'm not seeing anywhere that Bias T is mentioned on the website but I know there used to be something there. Should I add a new section to the instructions for it assuming I'm not missing it somewhere?

**Comment by adampbeardsley** [comment]
I noticed this yesterday... apparently we lost a whole section of the tutorial that explains how to use the GUI when we did the website update. Whoops. How git-ambitious are you feeling to go back in time and recover the old tutorial? If not, I can probably take a crack at it tomorrow.

Maybe this is related to the issue where danny asked for a GUI image from the new disk image.

**Comment by Alexandra202421** [comment]
I can certainly give it my best go but it might take me a while lol, I'll see what I can do!

**Comment by Alexandra202421** [comment]
I found the datataking section in merged pull request 50 and its definitely gone by danny's "clean up sidebar" request but I can't find where it disappeared in the middle of that, not sure if these images will post either

![image](https://github.com/user-attachments/assets/4e446dcd-4d4f-4616-8bca-8a498dd7fa4f)
![image](https://github.com/user-attachments/assets/282f0bae-20d8-462e-9aa2-bda60994cb01)
